### ISSUE TITLE
When using Supabase Auth, how do you relate to other tables using Drizzle?

### ISSUE THREAD

**Issue by HassanDev13** [rphlmr/old-drizzle-supabase-rls#1]
When using Supabase Auth, how do you relate to other tables using Drizzle?

**Comment by rphlmr** [comment]
You should be able to define the auth schema with the users table: https://orm.drizzle.team/docs/schemas#table-schemas

**Comment by rphlmr** [comment]
Check this commit: https://github.com/rphlmr/drizzle-supabase-rls/commit/fcc790a4c0731231feaeb103539c84b53bad1a63

I have manually edited the generated SQL to add `auth.users` in the constraint references because there is a bug on Drizzle kit about that.
